Fix the projection of tippyName when using ng-template
farengeyt451/ngx-tippy-wrapper pull request #48
Opened 2023-05-31 10:30 UTC by onaluf

This also adds [tippyContext] to pass a custom context to the template which solves #43

2023-05-31 10:34 UTC, onaluf commented
I hope this works for you, don't hesitate if there is any changes that you want me to make to this! I've also added a unit test that passes but on my box some other test where failing on `master`.

2023-07-04 15:51 UTC, farengeyt451 requested changes
Thank you for your MR)

2023-07-04 15:51 UTC, farengeyt451 commented on projects/ngx-tippy-wrapper/src/lib/ngx-tippy.directive.ts
> +  @Input() tippyContext: any;
`tippyContext` should be optional like previous attributes and I think it also should have some generic interface

2023-07-04 15:51 UTC, farengeyt451 commented on projects/ngx-tippy-wrapper/src/lib/services/ngx-view.service.ts
> +  getViewRefInstance(content: NgxTippyTemplate, tippyName?: string, tippyContext?: any): ViewRef {
Same here, pls don't use `any` type

2023-07-04 15:51 UTC, farengeyt451 commented on projects/ngx-tippy-wrapper/src/lib/ngx-tippy.directive.ts
For `tippyContext` attribute we need definitely try to handle case when `context` could be changed dynamically as in other attributes `(tippyName, ngxTippy, tippyProps, tippyClassName)`.

As example we can take such primitvie case:

```html
<button
  ngxTippy
  tippyName="ng-template-ref-plus-context"
  [ngxTippy]="tplctx"
  [tippyProps]="ngTemplateRef"
  [tippyContext]="templateContext"
>
  Element with tooltip
</button>

<ng-template
  #tplctx
  let-name
  let-foo="foo"
>
  <div class="t-template">
    <span class="t-template__name">Passed tippyName <b>{{ name }}</b> and context <b>{{ foo }}</b></span>
  </div>
</ng-template>
```

```ts
  templateContext!: Record<string, any>;

  ngOnInit() {
    this.templateContext = { foo: 'Hello' };

    setTimeout(() => {
      this.templateContext = { foo: 'World' };
    }, 1000);
  }
```

Need to handle this dynamic `context` changes

2023-07-04 15:51 UTC, farengeyt451 commented on projects/ngx-tippy-demo/src/app/app.component.html
As example we can use somthing simpler like:

```html
<button
  ngxTippy
  tippyName="ng-template-ref-plus-context"
  [ngxTippy]="tplctx"
  [tippyProps]="ngTemplateRef"
  [tippyContext]="templateContext"
>
  Element with tooltip
</button>

<ng-template
  #tplctx
  let-name
  let-foo="foo"
>
  <div class="t-template">
    <span class="t-template__name">Passed tippyName <b>{{ name }}</b> and context <b>{{ foo }}</b></span>
  </div>
</ng-template>
```

2023-07-04 15:51 UTC, farengeyt451 commented on README.md
> +| `tippyContext`   | any           | [tippyContext]="{ aKey: 'something' }" |
Better to provide interface instead of `any`

2023-07-12 10:01 UTC, onaluf commented
Hope this is to you liking, don't hesitate if you want other changes! I tried adding a unit test for change detection in the context but didn't manage to.

2023-07-12 21:47 UTC, merged